# Generated by Django 3.0.4 on 2022-09-03 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetail',
            name='subs',
            field=models.IntegerField(default=0),
        ),
    ]
