# Generated by Django 3.0.4 on 2022-02-03 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_details',
            name='link_chain',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='blog_details',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
