# Generated by Django 3.0.4 on 2022-02-03 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20220203_0816'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='blodg_id',
            new_name='blog_id',
        ),
    ]
