# Generated by Django 3.0.4 on 2022-02-10 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20220203_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog_details',
            name='blog_thumbnail',
            field=models.ImageField(default='/media/images/backbg.jpg', upload_to='thumbnails/'),
        ),
    ]
