# Generated by Django 3.0.4 on 2022-09-03 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_tags'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog_details',
            options={'ordering': ['-blog_clicks']},
        ),
    ]
