# Generated by Django 3.0.4 on 2022-09-03 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20220903_1355'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog_details',
            old_name='tags',
            new_name='tags_input',
        ),
    ]
